### ISSUE TITLE
Include Graphiti stuff only in api

### ISSUE THREAD

**Issue by mkamensky** [graphiti-api/graphiti-rails#52]
It seems that the stuff here:
https://github.com/graphiti-api/graphiti-rails/blob/2b787402f3247a5fdb27e0cb36f53522dac49557/lib/graphiti/rails.rb#L39
is included in all controllers, not just the ones that use Graphiti. Is it possible to opt-out?

**Comment by jspooner** [comment]
I have an existing API with existing `v1` and `v2` routes.  When I added a Graphiti `v3` route my request specs for `v2` started failing.  The root cause for this failure is `Graphiti::Rails:: wrap_graphiti_context` https://github.com/graphiti-api/graphiti-rails/blob/master/lib/graphiti/rails/context.rb#L26

```ruby
 NameError:
       undefined local variable or method `jsonapi_context' for #<Api::V2::Accounts::AutocompleteController:0x00007fc893742760>
     # ./app/controllers/api/v2/accounts/autocomplete_controller.rb:47:in `method_missing'
```

I can't explain why [respond_to?(:jsonapi_context)](https://github.com/graphiti-api/graphiti-rails/blob/master/lib/graphiti/rails/context.rb#L24) evaluates to **true** yet a call to `jsonapi_context` results in a `NameError`

My solution was to monkey patch this method like this.

```ruby
module Graphiti
  module Rails
    # Wraps controller actions in a [Graphiti Context](https://www.graphiti.dev/guides/concepts/resources#context) which points to the
    # controller instance by default.
    module Context
      def graphiti_context
        self
      end
    end
  end
end
```

**Comment by wagenet** [comment]
@mkamensky I do not believe it's currently possible to opt-out. What issues is it causing for you?

**Comment by wagenet** [comment]
@jspooner this sounds very odd. I don't have any specific leads offhand. If you're able to come up with a small reproduction I might be able to figure it out.

**Comment by mkamensky** [comment]
@wagenet Truth is I no longer remember, I think it had something to do with debugging, but I can no longer recall what... I see that I overrode `debug_graphiti` and `wrap_graphiti_context` with just `yield`, but I can't remember what was the reason, and whether it solved it.

**Comment by Ayat11** [comment]
Is it still not possible to opt-out? I have some controllers that need to use Graphiti and other that don't, so I'm getting errors for the ones that don't, is there a way to specify which controllers use graphiti?

**Comment by wagenet** [comment]
@Ayat11 Can you share one of the errors here?

**Comment by conwayje** [comment]
My org is seeing problems stemming from this everywhere-insertion as well and might need to migrate off of Graphiti because of it 😞 

We have some existing controllers (classic Rails controllers and a v1 API) that we don't want Graphiti to touch at all.  Our plan was for v2 to be the only Graphiti-powered portion of our app.

However, when we install `graphiti-rails`, certain cases break in those existing controllers.  For example, where one endpoint is supposed to respond with a specific error message, we instead get an exception from the sub-gem `rescue_registry` from @wagenet :

```
"Didn't expect RescueRegistry context to be set in controller"
```

Which breaks specs/expected behavior.  We're a bit scared to move forward with Graphiti given the fact that it touches huge portions of our app that we don't want it to touch at all, and it feels risky to go down this road even though our request/api specs are pretty thorough.  We may use the deprecated `graphiti` gem style or try to submit a PR to fix, but drawbacks in any case.

**Comment by richmolj** [comment]
@conwayje can you give us a tiny demo app that reproduces the error? Sounds like that's what @waganet needs to debug

**Comment by bilouw** [comment]
Hi !

I have the same problem ! When i try to sign_in with wrong password, the post to /sign_in return 200 OK instead of 401 because of this error:

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7089641/223881897-72d21a37-e43d-49d6-bacf-4f0c388c2afd.png">

As we can see, an 401 is raise but at the end it return an 200 (i'm pretty sure it's because of the error).

The weird thing is that i have another /sign_in page (on another devise model/namespace), and on this sign_in page, it don't raise the RescueRegistry Error, and the server return 401 correctly.

Don't know why ... any clues ? Also, how can we fix this error once and for all ?

**Comment by cagedartist** [comment]
We have the same issue as described by [conwayje](https://github.com/conwayje).  Non-Graphiti-related tests that expect errors are disrupted by an error message "Didn't expect RescueRegistry context to be set in controller"  - coming from somewhere in `process_action'. First line of stack trace is ... activerecord-6.1.7.3/lib/active_record/railties/controller_runtime.rb:27:in 'process_action' ...but line 27 is 'super', I believe.

**Comment by onwardmk** [comment]
I have the same issue. Is it recommended to use the deprecated `graphiti` gem without `graphiti-rails`?
